django_project/django_project/urls.py
from django.conf.urls import include, url
from django.http import HttpResponseRedirect
from django.contrib import admin
from portada import views
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'django_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^$', lambda r: HttpResponseRedirect('portada/')),
    #url(r'portada/', include('portada.urls', namespace='portada')),
    url(r'^$', lambda r: HttpResponseRedirect('noticias/')),
    url(r'^noticias/', include('noticias.urls', namespace='noticias')),
    url(r'^news/', include('news.urls', namespace='news')), 
    url(r'^equipos/', include('equipos.urls', namespace='equipos')),
    url(r'^teams/', include('teams.urls', namespace='teams')),
    url(r'^circuitos/', include('circuitos.urls', namespace='circuitos')),
    url(r'^racetracks/', include('racetracks.urls', namespace='racetracks')),
    url(r'^pilotos/', include('pilotos.urls', namespace='pilotos')),
    url(r'^riders/', include('riders.urls', namespace='riders')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sobre_nosotros/', 
    TemplateView.as_view(template_name="pag_estaticas/sobre_nosotros.html"),
    name='sobre_nostros'),
    url(r'^terminos_condiciones/',
    TemplateView.as_view(template_name="pag_estaticas/term_and_cond.html"),
    name='terminos_condiciones'),
]

django_project/news/urls.py
from django.conf.urls import url

from .views import(
        NewsList,
        NewsNew,
        NewsUpdated,
        NewsDelete
)

urlpatterns = [
        url(r'^$', NewsList.as_view(), name='list'),
        url(r'^new$', NewsNew.as_view(), name='new'),
        url(r'^edit/(?P<pk>\d+)$', NewsUpdated.as_view(), name='edit'),
        url(r'^delete/(?P<pk>\d+)$', NewsDelete.as_view(), name='delete'),
]

django_project/riders/urls.py
from django.conf.urls import url

from .views import(
        RiderList,
        RiderDetail,
        RiderNew,
        RiderUpdated,
        RiderDelete
)

urlpatterns = [
        url(r'^$', RiderList.as_view(), name='list'),
        url(r'^(?P<slug>[\w-]+)/$', RiderDetail.as_view(), name='detail'),
        url(r'^new$', RiderNew.as_view(), name='new'),
        url(r'^edit/(?P<pk>\d+)$', RiderUpdated.as_view(), name='edit'),
        url(r'^delete/(?P<pk>\d+)$', RiderDelete.as_view(), name='delete'),

]

django_project/riders/models.py
from __future__ import unicode_literals

from django.db import models

from django.db.models.signals import pre_save
from django.utils.text import slugify
from teams.models import Team
class Rider(models.Model):
        name = models.CharField(max_length=255)
        team = models.ForeignKey('teams.Team',related_name='rider_team', on_delete=models.CASCADE, blank=True)
        biography = models.TextField()
        rider_profile = models.ImageField(blank=True)
        source = models.CharField(max_length=255, blank=True)
        rider_number = models.IntegerField(default=0)
	competition_status = models.CharField(max_length=255, blank=True)
        slug = models.CharField(max_length=255, default='rider', editable=True)

        class Meta:
                ordering = ('rider_number',)

        def __unicode__(self):
                return self.name

django_project/riders/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
        CreateView,
        UpdateView,
        DeleteView
)
from django.core.urlresolvers import reverse_lazy
from .models import Rider


class RiderList(ListView):
        model = Rider

class RiderDetail(DetailView):
        model = Rider

class RiderNew(LoginRequiredMixin, CreateView):
        model = Rider
        success_url = reverse_lazy('riders:list')
        fields = ['name','team','rider_number','biography','rider_profile','source']

class RiderUpdated(LoginRequiredMixin, UpdateView):
        model = Rider
        success_url = reverse_lazy('riders:list')
        fields = ['name','team','rider_number','biography','rider_profile','source']

class RiderDelete(LoginRequiredMixin, DeleteView):
        model = Rider
        success_url = reverse_lazy('riders:list')

django_project/templates/riders/rider_detail.html
{% extends "base_en.html" %}

{% block page_title %}
        {{ rider.name }}
{% endblock %}
{% block content%}
        <div class="container">
                <a class="material_design_arrow" href="/riders">&lt; Riders</a>
        </div>
        <div class="detail_info">
		<p class="lang_icon_first"><a href="/pilotos/{{ rider.slug }}"><img src="/media/es_flag.jpg"></a></p>
		<p class="lang_icon_second"><a href="/riders/{{ rider.slug }}"><img src="/media/uk_flag.jpg"></a></p>
                {% if rider.rider_profile  %}
                        <p><img class="perfil_piloto" alt="{{ rider.name }}" src={{ rider.rider_profile.url }}></p>
                        <p class="fuente_archivos_media">Source: {{ rider.source  }}</p>
                {% endif %}
                <h1>{{ rider.name }} | {{ rider.rider_number }}</h1>
                <h4><a href="/teams/{{ rider.team.slug}}">{{ rider.team }}</a></h4>
                {{ rider.biography|safe }}
        </div>

{% endblock %}
</body>
</html>

django_project/templates/riders/rider_list.html
{% extends "base_en.html" %}

{% block page_title %}
	Riders from the MotoGP championship
{% endblock %}
        {% block content%}
                <ul class="lista_items_principal">
			<p class="lang_icon_first"><a href="/pilotos/"><img src="/media/es_flag.jpg"></a></p>
                        <p class="lang_icon_second"><a href="/riders/"><img src="/media/uk_flag.jpg"></a></p>
                        {% for rider in object_list %}
				{% if rider.competition_status == "Active" %}
                                	<li class="col-xs-12 col-sm-6 col-md-4">
                                        	<div class="contenedor-carta" data-url="{% url "riders:detail" rider.slug %}">
                                                	{% if rider.rider_profile %}
								<img src={{ rider.rider_profile.url }}>
							{% endif %}
                                                	<a href="{% url "riders:detail" rider.slug %}">
                                                        	{{ rider.name }} | {{ rider.rider_number }}
                                                	</a>
                                        	</div>
                                	</li>
				{% endif %}
                        {% endfor %}
                </ul>
        {% endblock %}

</body>
</html>