django_project/django_project/urls.py
from django.conf.urls import include, url
from django.http import HttpResponseRedirect
from django.contrib import admin
from portada import views
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'django_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^$', lambda r: HttpResponseRedirect('portada/')),
    #url(r'portada/', include('portada.urls', namespace='portada')),
    url(r'^$', lambda r: HttpResponseRedirect('noticias/')),
    url(r'^noticias/', include('noticias.urls', namespace='noticias')),
    url(r'^news/', include('news.urls', namespace='news')), 
    url(r'^equipos/', include('equipos.urls', namespace='equipos')),
    url(r'^teams/', include('teams.urls', namespace='teams')),
    url(r'^circuitos/', include('circuitos.urls', namespace='circuitos')),
    url(r'^racetracks/', include('racetracks.urls', namespace='racetracks')),
    url(r'^pilotos/', include('pilotos.urls', namespace='pilotos')),
    url(r'^riders/', include('riders.urls', namespace='riders')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sobre_nosotros/', 
    TemplateView.as_view(template_name="pag_estaticas/sobre_nosotros.html"),
    name='sobre_nostros'),
    url(r'^terminos_condiciones/',
    TemplateView.as_view(template_name="pag_estaticas/term_and_cond.html"),
    name='terminos_condiciones'),
]

django_project/news/urls.py
from django.conf.urls import url

from .views import(
        NewsList,
        NewsNew,
        NewsUpdated,
        NewsDelete
)

urlpatterns = [
        url(r'^$', NewsList.as_view(), name='list'),
        url(r'^new$', NewsNew.as_view(), name='new'),
        url(r'^edit/(?P<pk>\d+)$', NewsUpdated.as_view(), name='edit'),
        url(r'^delete/(?P<pk>\d+)$', NewsDelete.as_view(), name='delete'),
]

django_project/pilotos/urls.py
from django.conf.urls import url

from .views import(
	PilotoLista,
	PilotoDetalle,
	PilotoNuevo,
	PilotoActualizado,
	PilotoEliminar
)

urlpatterns = [
	url(r'^$', PilotoLista.as_view(), name='lista'),
	url(r'^(?P<slug>[\w-]+)/$', PilotoDetalle.as_view(), name='detalle'),
	url(r'^nuevo$', PilotoNuevo.as_view(), name='nuevo'),
	url(r'^editar/(?P<pk>\d+)$', PilotoActualizado.as_view(), name='editar'),
	url(r'^eliminar/(?P<pk>\d+)$', PilotoEliminar.as_view(), name='eliminar'),

]

django_project/pilotos/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from equipos.models import Equipo
class Piloto(models.Model):
	nombre = models.CharField(max_length=255)
	equipo = models.ForeignKey('equipos.Equipo',related_name='equipo_del_piloto', on_delete=models.CASCADE, blank=True)
	biografia = models.TextField()
	perfil_piloto = models.ImageField(blank=True)
	fuente = models.CharField(max_length=255, blank=True)
	numero_dorsal = models.IntegerField(default=0)
	estado_competicion = models.CharField(max_length=255, blank=True)
	slug = models.CharField(max_length=255, default='piloto', editable=True)

	class Meta:
		ordering = ('numero_dorsal',)

	def __unicode__(self):
		return self.nombre

django_project/pilotos/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
	CreateView, 
	UpdateView,
	DeleteView
)
from django.core.urlresolvers import reverse_lazy
from .models import Piloto


class PilotoLista(ListView):
	model = Piloto

class PilotoDetalle(DetailView):
	model = Piloto

class PilotoNuevo(LoginRequiredMixin, CreateView):
	model = Piloto
	success_url = reverse_lazy('pilotos:lista')
	fields = ['nombre','equipo','numero_dorsal','biografia','perfil_piloto','fuente']

class PilotoActualizado(LoginRequiredMixin, UpdateView):
	model = Piloto
	success_url = reverse_lazy('pilotos:lista')
	fields = ['nombre','equipo','numero_dorsal','biografia','perfil_piloto','fuente']

class PilotoEliminar(LoginRequiredMixin, DeleteView):
	model = Piloto
	success_url = reverse_lazy('pilotos:lista')

django_project/templates/pilotos/piloto_confirm_delete.html
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas eliminar el piloto "{{ object }}"?
    <input type="submit" value="Submit" />
</form>

django_project/templates/pilotos/piloto_detail.html
{% extends "base.html" %}

{% block page_title %}
	{{ piloto.nombre }}
{% endblock %}
{% block content%}
	<div class="container">
		<a class="material_design_arrow" href="/pilotos">&lt; Pilotos</a>
	</div>
	<div class="detail_info">
		<p class="lang_icon_first"><a href="/pilotos/{{ piloto.slug }}"><img src="/media/es_flag.jpg"></a></p>
                <p class="lang_icon_second"><a href="/riders/{{ piloto.slug }}"><img src="/media/uk_flag.jpg"></a></p>
		{% if piloto.perfil_piloto  %}
			<p><img class="perfil_piloto" alt="{{piloto.nombre}}" src={{ piloto.perfil_piloto.url }}></p>
			<p class="fuente_archivos_media">Fuente: {{ piloto.fuente  }}</p>
		{% endif %}	
		<h1>{{ piloto.nombre }} | {{ piloto.numero_dorsal }}</h1>
		<h4><a href="/equipos/{{ piloto.equipo.slug}}">{{ piloto.equipo  }}</a></h4>
		{{ piloto.biografia|safe }}
	</div>
		
{% endblock %}
</body>
</html>

django_project/templates/pilotos/piloto_form.html
{% extends "base.html" %}

{% block page_title %}
	Nuevo Piloto
{% endblock %}
	{% block content%}
		<h1>Nuevo Piloto</h1>

		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p}}
			<button type="submit">Submit</button>
		</form>
	{% endblock %}
	
</body>
</html>

django_project/templates/pilotos/piloto_list.html
{% extends "base.html" %}

{% block page_title %}
	Pilotos que compiten en el campeonato de MotoGP
{% endblock %}
	{% block content%}
		<ul class="lista_items_principal">
		<p class="lang_icon_first"><a href="/pilotos/"><img src="/media/es_flag.jpg"></a></p>
                <p class="lang_icon_second"><a href="/riders/"><img src="/media/uk_flag.jpg"></a></p>
			{% for piloto in object_list %}
				{% if piloto.estado_competicion == "Activo" %}
					<li class="col-xs-12 col-sm-6 col-md-4">
						<div class="contenedor-carta" data-url="{% url "pilotos:detalle" piloto.slug %}">
							<img src={{ piloto.perfil_piloto.url }}>
							<a href="{% url "pilotos:detalle" piloto.slug %}">
								{{ piloto.nombre }} | {{ piloto.numero_dorsal }}
							</a>
						</div>
					</li>
				{% endif %}
			{% endfor %}
		</ul>
	{% endblock %}
	
</body>
</html>