django_project/django_project/urls.py
from django.conf.urls import include, url
from django.http import HttpResponseRedirect
from django.contrib import admin
from portada import views
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'django_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^$', lambda r: HttpResponseRedirect('portada/')),
    #url(r'portada/', include('portada.urls', namespace='portada')),
    url(r'^$', lambda r: HttpResponseRedirect('noticias/')),
    url(r'^noticias/', include('noticias.urls', namespace='noticias')),
    url(r'^news/', include('news.urls', namespace='news')), 
    url(r'^equipos/', include('equipos.urls', namespace='equipos')),
    url(r'^teams/', include('teams.urls', namespace='teams')),
    url(r'^circuitos/', include('circuitos.urls', namespace='circuitos')),
    url(r'^racetracks/', include('racetracks.urls', namespace='racetracks')),
    url(r'^pilotos/', include('pilotos.urls', namespace='pilotos')),
    url(r'^riders/', include('riders.urls', namespace='riders')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sobre_nosotros/', 
    TemplateView.as_view(template_name="pag_estaticas/sobre_nosotros.html"),
    name='sobre_nostros'),
    url(r'^terminos_condiciones/',
    TemplateView.as_view(template_name="pag_estaticas/term_and_cond.html"),
    name='terminos_condiciones'),
]

django_project/news/urls.py
from django.conf.urls import url

from .views import(
        NewsList,
        NewsNew,
        NewsUpdated,
        NewsDelete
)

urlpatterns = [
        url(r'^$', NewsList.as_view(), name='list'),
        url(r'^new$', NewsNew.as_view(), name='new'),
        url(r'^edit/(?P<pk>\d+)$', NewsUpdated.as_view(), name='edit'),
        url(r'^delete/(?P<pk>\d+)$', NewsDelete.as_view(), name='delete'),
]

django_project/teams/urls.py
from django.conf.urls import url

from .views import(
        TeamList,
        TeamDetail,
        TeamNew,
        TeamUpdated,
        TeamDelete
)

urlpatterns = [
        url(r'^$', TeamList.as_view(), name='list'),
        url(r'^(?P<slug>[\w-]+)/$', TeamDetail.as_view(), name='detail'),
        url(r'^nuevo$', TeamNew.as_view(), name='new'),
        url(r'^edit/(?P<pk>\d+)$', TeamUpdated.as_view(), name='edit'),
        url(r'^delete/(?P<pk>\d+)$', TeamDelete.as_view(), name='delete'),
]

django_project/teams/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify

class Team(models.Model):
        name = models.CharField(max_length=255)
        team_riders = models.ManyToManyField('riders.Rider',related_name='team_riders',blank=True)
        team_image = models.ImageField(blank=True)
        source = models.CharField(max_length=255, blank=True)
        history = models.TextField()
	status = models.CharField(max_length=255, blank=True)
        slug = models.CharField(max_length=255, default='team', editable=True)



        class Meta:
                ordering = ('name',)

        def __unicode__(self):
                return self.name

django_project/teams/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
        CreateView,
        UpdateView,
        DeleteView,
)
from django.core.urlresolvers import reverse_lazy
from .models import Team

class TeamList(ListView):
        model = Team

class TeamDetail(DetailView):
        model = Team

class TeamNew(LoginRequiredMixin, CreateView):
        model = Team
        success_url = reverse_lazy('teams:list')
        fields = ['name','team_riders','history','team_image','source']

class TeamUpdated(LoginRequiredMixin, UpdateView):
        model = Team
        success_url= reverse_lazy('teams:list')
        fields = ['name','team_riders','history','team_image','source']

class TeamDelete(LoginRequiredMixin, DeleteView):
        model = Team
        success_url = reverse_lazy('teams:list')

django_project/templates/teams/team_confirm_delete.html
▽
<form method="post">{% csrf_token %}
    Are you sure that you want to delete the team "{{ object }}"?
    <input type="submit" value="Submit" />
</form>

django_project/templates/teams/team_detail.html
{% extends "base_en.html" %}

{% block page_title %}
        {{ team.name }}
{% endblock %}
{% block content%}
        <div class="container">
                <a class="material_design_arrow" href="/teams">&lt; Teams</a>
        </div>
        <div class="detail_info">
		<p class="lang_icon_first"><a href="/equipos/{{ team.slug }}"><img src="/media/es_flag.jpg"></a></p>
                <p class="lang_icon_second"><a href="/teams/{{ team.slug }}"><img src="/media/uk_flag.jpg"></a></p>
                <h1>{{ team.name }}</h1>
		{% if team.team_image %}
                <p><img class="perfil_piloto" alt="{{team.name}}" src="{{ team.team_image.url }}"></p>
                <p class="fuente_archivos_media">Source: {{ team.source  }}</p>
		{% endif %}
                {% if team.team_riders %}
                        <h2>Team's riders:</h2>
                        <ul class="pilotos_de_equipo">
                        {% for rider in team.team_riders.all %}
                                <li><h4><a href="/riders/{{ rider.slug }}">{{ rider.name }}</a></h4></li>
                        {% endfor %}
                        </ul>
                {% endif %}
                {{ team.history|safe }}
        </div>

{% endblock %}
</body>
</html>

django_project/templates/teams/team_form.html
{% extends "base_en.html" %}

{% block page_title %}
        New Team
{% endblock %}
        {% block content%}
                <h1>New Team</h1>

                <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit">Submit</button>
                </form>
        {% endblock %}

</body>
</html>

django_project/templates/teams/team_list.html
{% extends "base_en.html" %}

{% block page_title %}
        Teams participating in the MotoGP championship
{% endblock %}
        {% block content%}
                <ul class="lista_items_principal">
			<p class="lang_icon_first"><a href="/equipos/"><img src="/media/es_flag.jpg"></a></p>
                	<p class="lang_icon_second"><a href="/teams/"><img src="/media/uk_flag.jpg"></a></p>
                        {% for team in object_list %}
				{% if team.status == "Active" %}
                                	<li class="col-xs-12 col-sm-6 col-md-4">
                                        	<div class="contenedor-carta" data-url="{% url "teams:detail" team.slug %}">
                                                	{% if team.team_image %}
								<img src="{{ team.team_image.url }}">
							{% endif %}
                                                	<a class="esconder_texto_largo" href="{% url "teams:detail" team.slug %}">
                                                        	{{ team.name }}
                                                	</a>
                                        	</div>
                                	</li>
				{% endif %}
                        {% endfor %}
                </ul>
        {% endblock %}

</body>
</html>