django_project/django_project/urls.py
from django.conf.urls import include, url
from django.http import HttpResponseRedirect
from django.contrib import admin
from portada import views
from django.views.generic import TemplateView
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'django_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^$', lambda r: HttpResponseRedirect('portada/')),
    #url(r'portada/', include('portada.urls', namespace='portada')),
    url(r'^$', lambda r: HttpResponseRedirect('noticias/')),
    url(r'^noticias/', include('noticias.urls', namespace='noticias')),
    url(r'^news/', include('news.urls', namespace='news')), 
    url(r'^equipos/', include('equipos.urls', namespace='equipos')),
    url(r'^teams/', include('teams.urls', namespace='teams')),
    url(r'^circuitos/', include('circuitos.urls', namespace='circuitos')),
    url(r'^racetracks/', include('racetracks.urls', namespace='racetracks')),
    url(r'^pilotos/', include('pilotos.urls', namespace='pilotos')),
    url(r'^riders/', include('riders.urls', namespace='riders')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sobre_nosotros/', 
    TemplateView.as_view(template_name="pag_estaticas/sobre_nosotros.html"),
    name='sobre_nostros'),
    url(r'^terminos_condiciones/',
    TemplateView.as_view(template_name="pag_estaticas/term_and_cond.html"),
    name='terminos_condiciones'),
]

django_project/news/urls.py
from django.conf.urls import url

from .views import(
        NewsList,
        NewsNew,
        NewsUpdated,
        NewsDelete
)

urlpatterns = [
        url(r'^$', NewsList.as_view(), name='list'),
        url(r'^new$', NewsNew.as_view(), name='new'),
        url(r'^edit/(?P<pk>\d+)$', NewsUpdated.as_view(), name='edit'),
        url(r'^delete/(?P<pk>\d+)$', NewsDelete.as_view(), name='delete'),
]

django_project/racetracks/urls.py
from django.conf.urls import url
from .views import(
        RacetrackList,
        RacetrackDetail,
        RacetrackNew,
        RacetrackUpdated,
        RacetrackDelete,
)
urlpatterns = [
        url(r'^$', RacetrackList.as_view(), name='list'),
        url(r'^(?P<slug>[\w-]+)/$', RacetrackDetail.as_view(), name='detail'),
        url(r'^new$', RacetrackNew.as_view(), name='new'),
        url(r'^edit/(?P<pk>\d+)$', RacetrackUpdated.as_view(), name='edit'),
        url(r'^delete/(?P<pk>\d+)$', RacetrackDelete.as_view(), name='delete'),
]

django_project/racetracks/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import date

class Racetrack(models.Model):
        name = models.CharField(max_length=255)
        description = models.TextField()
        track_image = models.ImageField(blank=True)
        event_date = models.DateField(auto_now_add=False)
        slug = models.CharField(max_length=255, default='racetrack', editable=True)

        class Meta:
                ordering = ('event_date',)

        def coming_race(self):
                return self.event_date > date.today()
        def race_ongoing(self):
                return self.event_date == date.today()

        def __unicode__(self):
                return self.name

django_project/racetracks/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
        CreateView,
        UpdateView,
        DeleteView,
)
from django.core.urlresolvers import reverse_lazy
from .models import Racetrack

class RacetrackList(ListView):
        model = Racetrack

class RacetrackDetail(DetailView):
        model = Racetrack

class RacetrackNew(LoginRequiredMixin, CreateView):
        model = Racetrack
        success_url = reverse_lazy('racetracks:list')
        fields = ['name','description','event_date','slug']

class RacetrackUpdated(LoginRequiredMixin, UpdateView):
        model = Racetrack
        success_url = reverse_lazy('racetracks:list')
	fields = ['name','description','event_date','slug']

class RacetrackDelete(LoginRequiredMixin, DeleteView):
        model = Racetrack
        success_url = reverse_lazy('racetracks:list')

django_project/templates/racetracks/racetrack_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete this racetrack "{{ object }}"?
    <input type="submit" value="Submit" />
</form>

django_project/templates/racetracks/racetrack_detail.html
{% extends "base_en.html" %}

{% block page_title %}
        {{ racetrack.name }}
{% endblock %}
{% block content%}
        <div class="container">
                <a class="material_design_arrow" href="/racetracks">&lt; Racetracks</a>
        </div>
        <div class="detail_info">
		<p class="lang_icon_first"><a href="/circuitos/{{ racetrack.slug  }}"><img src="/media/es_flag.jpg"></a></p>
                <p class="lang_icon_second"><a href="/racetracks/{{ racetrack.slug  }}"><img src="/media/uk_flag.jpg"></a></p>
                <h1>{{ racetrack.name }}</h1>
		{% load i18n %}
                <h4>Grand Prix Date: <br>{{ racetrack.event_date }}</h4>
                <br>
                {{ racetrack.description|safe }}
                <img class="{{ racetrack.name }}" src="{{ racetrack.track_image.url }}" alt="{{ racetrack.name }}">
        </div>

{% endblock %}
</body>
</html>

django_project/templates/racetracks/racetrack_form.html
{% extends "base_en.html" %}

{% block page_title %}
        New Racetrack
{% endblock %}
        {% block content%}
                <h1>New Racetrack</h1>

                <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit">Submit</button>
                </form>
        {% endblock %}

</body>
</html>

django_project/templates/racetracks/racetrack_list.html
{% extends "base_en.html" %}

{% block page_title %}
        Racetracks of the MotoGP championship
{% endblock %}
        {% block content%}
                <ul class="lista_items_principal">
			<p class="lang_icon_first"><a href="/circuitos/"><img src="/media/es_flag.jpg"></a></p>
                	<p class="lang_icon_second"><a href="/racetracks/"><img src="/media/uk_flag.jpg"></a></p>
                        {% for racetrack in object_list %}
                                {% if racetrack.coming_race %}
                                        <li>
                                                <a href="{% url "racetracks:detail" racetrack.slug %}">
                                                        {{ racetrack.name }} |
                                                </a>
                                        </li>
                                {% elif racetrack.race_ongoing %}
                                        <li>
                                                <a href="{% url "racetracks:detail" racetrack.slug %}">
                                                {{ racetrack.name }} | <span class="evento_en_curso">ONGOING GP</span>
                                                </a>
                                        </li>
                                {% else %}
                                        <li>
                                                <a href="{% url "racetracks:detail" racetrack.slug %}">
                                                        {{ racetrack.name }} | <span class="evento_pasado">FINISHED GP</span>
                                                </a>
                                        </li>
                                {% endif %}
                        {% endfor %}
                </ul>
        {% endblock %}

</body>
</html>